vm/CMakeLists.txt

#5 
The latest version of `tokenizers-cpp` can set the target macOS version. (added at https://github.com/mlc-ai/tokenizers-cpp/pull/52)
But the `tokenizers-cpp` version that the `mlc-llm` is using is [4bb7533](https://github.com/mlc-ai/tokenizers-cpp/tree/4bb753377680e249345b54c6b10e6d0674c8af03) which doesn't have that.
So let the `mlc-llm` use the latest `tokenizers-cpp` [here](https://github.com/brekkylab/mlc-llm/commits/3b8165524fdb79fd3255395432ac70a7734a22ef/), and ailoy use the `mlc-llm`.
The macOS version setting merged into `tokenizers-cpp` later than its `huggingface/tokenizers` update to `0.21.0` (at https://github.com/mlc-ai/tokenizers-cpp/pull/62), we need to use `0.21.0` for this.
And the `0.21.0` of `huggingface/tokenizers` includes …

build: bump `tokenizers-cpp` version as latest

---

bindings/js-node/src/agent.ts
bindings/js-node/tests/agent.spec.ts
bindings/python/ailoy/agent.py
vm/src/language.cpp
vm/src/mlc_llm/chat_template_engine.cpp
vm/src/mlc_llm/chat_template_engine.hpp
vm/tests/test_tvm_language_model.cpp

- `reasoning`, `do_reasoning` -> `enable_reasoning`
- `ignore_reasoning` -> `ignore_reasoning_messages`

Fix and unify parameter names related to reasoning

---

bindings/python/ailoy/agent.py
examples/python/movie_agent.py

Some typing classes (like `List`, `Tuple`, etc.) are deprecated and replaced by pre-existing classes from python 3.9.
If we don't need to support python 3.8 or below(these versions are in end-of-life.), we had better not to use those classes.
So this PR just replace those with the existing classes
`typing.Union[T, U]` and `typing.Optional[T] == typing.Union[T, None]` can be replaced with `T | U` and `T | None` from python 3.10. But we still need to python 3.9 and these are not even deprecated, so those would remains.

Deprecated typing

---

vm/src/mlc_llm/model_cache.cpp
vm/src/mlc_llm/model_cache.hpp

Previously, hard-coded `CACHE_ROOT` and `R2_BASE_URL` controls remote & local cache roots.
This PR makes the user can control the path of these cache-related directories, via environment variable
- `AILOY_CACHE_ROOT`: Can change local cache root
- `AILOY_REMOTE_CACHE_BASE_URL`: Can change remote file server

make cache root & r2 base url configurable

---

vm/CMakeLists.txt

Currently, the customized version of `minja` being used due to the Qwen3 supports.
Now the official [minja](https://github.com/google/minja) supports Qwen3, so bringing it back.

build: use the official version of minja instead of customized

---

bindings/js-node/src/agent.ts
bindings/python/ailoy/agent.py
examples/news_agent_js_node/src/index.ts
examples/python/news_agent.py
presets/tools/tmdb.json

During writing the example code for NY Times tool, I realized that there is no handy way to authenticate the REST requests through the query params in python. (in node.js, anonymous class object can cover this.)
So I changed functions to get the proper 'callable' instead of `ToolAuthenticator`. 
I just added `__call__()` into the `ToolAuthenticator` to make it callable, so existing `ToolAuthenticator` is still available.
```python
if callable(authenticator):
request = authenticator(request)
```
To apply this on nodejs, It is just using the function.
Request for comments on this kind of changes on API!

Pass function as authenticator

---

vm/CMakeLists.txt

Since my patch(about mt/md) merged into `mlc-ai/tokenizers-cpp`, we can use official tokenizers-cpp.
This PR is paired with https://github.com/brekkylab/mlc-llm/pull/3

update tokenizer cpp

---

vm/src/mlc_llm/embedding_model.cpp
vm/src/mlc_llm/language_model.cpp
vm/src/mlc_llm/mlc_llm_engine.cpp
vm/src/mlc_llm/model_cache.cpp
vm/src/mlc_llm/model_cache.hpp
vm/src/mlc_llm/tvm_model.cpp
vm/tests/test_model_cache.cpp

- Added `SigintCatcher` which registers sigint handler and restores it via RAII pattern.
- `download_file_with_progress()` initializes the above `SigintCatcher` at the beginning, and returns the corresponding error message immediately when SIGINT has been detected.
- `get_model` now returns a struct `model_cache_get_result_t` which stores `success` and optional `error_message`. The users of `get_model` (currently including `tvm_model_t` and `mlc_llm_engine_t`) are responsible for handling errors when `success` is false. Components (`tvm_embedding_model` and `tvm_language_model`) may return `error_output_t` if such exception has been catched.
- Added a test case `SigintWhileGetModel` for testing SIGINT situations.
- Decided to show progress bars by default, which looks better for user …

Capture sigint while downloading models

---

bindings/python/ailoy/agent.py

Add missed setting of default system message in python `Agent`

fix: add setting default system message for python Agent

---

bindings/js-node/src/agent.ts
bindings/js-node/src/vector_store.ts
bindings/python/ailoy/vector_store.py
vm/src/mlc_llm/embedding_model.cpp
vm/src/mlc_llm/embedding_model.hpp
vm/src/mlc_llm/language_model.cpp
vm/src/mlc_llm/tvm_model.hpp
vm/tests/test_tvm_embedding_model.cpp
vm/tests/test_tvm_language_model.cpp

#20 
Add feature to get device id (as `int_t` or `uint_t` value) as component attribute, then use the device with that device id.
Device type is still set by the target environment, but the device id can be configured.
First, it checks if a device with the given device id exists, and if so, it uses it.
If not, it checks again with id 0, and if so, it uses it(logs this situation with `info` level), otherwise it returns `error_output_t`.
- Code for getting the device for embedding models and language models is integrated.
- `tvm_model_t::prepare_engine()` is removed.
- `tvm_embedding_model_t` gets device instead of getting it internally.
- Added test to try to get the device with id `1`

Device selection

---

README.md
bindings/js-node/src/agent.ts
bindings/js-node/src/vector_store.ts
bindings/js-node/tests/agent.spec.ts
bindings/python/ailoy/agent.py
bindings/python/ailoy/vector_store.py
bindings/python/tests/test_0_runtime_sync.py
bindings/python/tests/test_2_agent.py
examples/movie_agent_js_node/src/index.ts
examples/news_agent_js_node/src/index.ts
examples/python/mcp_github_agent.py
examples/python/movie_agent.py
examples/python/news_agent.py
examples/simple_rag_electron/src/ipc.ts

Use huggingface model ids for Agent, VectorStore APIs just like Runtime APIs, not to confuse users.

refactor: use huggingface model id instead of custom id for models

---

README.md
bindings/python/README.md
bindings/python/pyproject.toml

Currently we're having trouble on uploading our package to PyPI due to the reason explained in https://github.com/pypi/support/issues/6451.
The response from PyPI has been extremely slow, making it unclear when we will be able to use the name `ailoy`. Therefore, it has become inevitable for us to change and use the package name as `ailoy-py` for a while.

Rename python package: `ailoy` -> `ailoy-py`

---

bindings/js-node/src/agent.ts
bindings/js-node/src/index.ts
bindings/js-node/tests/agent.spec.ts
bindings/python/ailoy/agent.py
docs/docs/concepts/tools.mdx
presets/tools/calculator.json

As we decided to call the 'universal tool' as 'built-in tool', renaming it.

refactor: rename `universal tool` -> `builtin tool`

---

CMakeLists.txt
bindings/js-node/README.md
bindings/js-node/package.json
bindings/js-node/tests/agent.spec.ts
bindings/python/CMakeLists.txt
bindings/python/README.md
bindings/python/ailoy/agent.py
bindings/python/ailoy/vector_store.py
examples/simple_rag_electron/README.md
examples/simple_rag_electron/package-lock.json
examples/simple_rag_electron/package.json
examples/simple_rag_electron/src/global.d.ts
examples/simple_rag_electron/src/ipc.ts
examples/simple_rag_electron/src/preload.ts
examples/simple_rag_electron/src/ui/app.tsx
examples/simple_rag_electron/vite.main.config.mts
vm/src/mlc_llm/language_model.cpp
vm/src/mlc_llm/mlc_llm_engine.cpp
vm/src/mlc_llm/mlc_llm_engine.hpp

Resolves #67 
- Fix the bug that keyword parameters `attrs` does not being changed on next instance initializations (for both `Agent` and `VectorStore`)
- `mlc_llm_engine_t` object is not being freed since its reference count remains in unordered_map `engines`. This unordered_map was initially introduced for reusing parameters and saving memory usages, but we need to find another way to achieve this (left TODO comments).

Fix(python): `attrs` kwargs not changed on Agent and VectorStore

---

bindings/js-node/src/agent.ts
bindings/python/ailoy/agent.py

Assistant text messages were unintentionally missing from `messages` within the `Agent`.
Although the previous response of AI is relatively meaningless to AI behavior, the gap in the overall context may have affected AI's final response to some extent.
So, this modification may improve the response performance of AI based on Agent.
Practically, some of the weird responses seem to have improved.

fix: put missed assistant message in `Agent` messages

---

bindings/js-node/src/agent.ts
bindings/js-node/src/runtime.ts
bindings/python/ailoy/agent.py
bindings/python/ailoy/runtime.py

resolves #63 
Not only an agent can be deleted after the runtime has stopped when the program terminates, but an agent can also use an invalid runtime anytime in some circumstances. (See the following code.)
So we should raise an error properly when the agent try to use it instead of preventing that situation.
```python
rt = Runtime()
rt.stop()
agent = Agent(rt, ...)  # AttributeError: 'NoneType' object has no attribute 'send_type2'
```
However, in `Agent.delete()`, it could be better to just skip the Runtime task rather than raising errors.

Validate runtime client before using

---

bindings/js-node/src/agent.ts
bindings/js-node/src/mcp.ts
bindings/js-node/tests/agent.spec.ts
bindings/python/ailoy/agent.py
bindings/python/ailoy/mcp.py
bindings/python/tests/test_2_agent.py
examples/mcp_github_agent_py/mcp_github_agent.py

Previously, MCP servers were launched and terminated on-demand each time the agent attempted to list or call tools. This PR introduces a persistent lifecycle for MCP servers, ensuring they remain active until explicitly removed or when the agent itself is deleted.
* **Python**
* `MCPServer` now spawns a **dedicated subprocess** that acts as a bridge between the main process and the MCP stdio server.
* Initially it was implemented in `threading`-based approach, but it was unreliable in certain environments (e.g., `pytest`).
* Communication between processes is handled via `multiprocessing.Pipe` using structured, type-safe Pydantic messages (`RequestMessage` and `ResponseMessage`).
* The `stdio_client` async context is maintained throughout the subprocess lifecycle and is properly cleaned …

Persistent MCP Server Lifecycle Management

---

bindings/python/ailoy/runtime.py

[This issue](https://github.com/brekkylab/ailoy/issues/66) still happens, so we decided to add a slight sleep between retrying connection.

Fix: add slight sleep on runtime connection failed

---

bindings/js-node/src/agent.ts
bindings/python/ailoy/agent.py

OpenAI accepts tool names with pattern `^[a-zA-Z0-9_-]+$` only. If violated, it returns the following error.
```json
{
"error": {
"message": "Invalid 'tools[0].function.name': string does not match pattern. Expected a string that matches the pattern '^[a-zA-Z0-9_-]+$'.",
"type": "invalid_request_error",
"param": "tools[0].function.name",
"code": "invalid_value"
}
}
```
But our MCP tool names are prefixed with `/` separator, which is not included in the pattern. Hence this PR replaces the separator with `-`.
Verified that it works with openai now.

Fix tool name prefix for MCP tools

---

.github/workflows/build_node_windows.yaml
.github/workflows/build_python_windows.yaml

The link for OpenSSL 3.5.0 has been disappeared, so we need to update it.

Windows: update openssl to 3.5.1

---

vm/CMakeLists.txt
vm/tests/test_tokenizers.cpp
vm/tests/test_tokenizers.html

- We suffered from slow initialization of tokenizer class in browser environment, and the reason was sanitizer link options (`-fsanitize=undefined -fsanitize=address`) added in test executables. We fixed it by removing these options on Emscripten build time.
- We found that there's `-DCOMPILE_WASM_RUNTIME` compile definition in official mlc-ai/web-tokenizers build script (https://github.com/mlc-ai/tokenizers-cpp/blob/main/web/build.sh#L8). This is for preventing thread parallelism which leads to error on WASM runtime (see https://github.com/mlc-ai/tokenizers-cpp/pull/42). So we provide the same compile definition on Emscripten build time.
- Added the test executable (and html) for testing tokenizers only.

Add test for tokenizers

---

bindings/js-web/src/agent.ts
bindings/js-web/tests/agent-claude.test.ts
bindings/js-web/tests/agent-gemini.test.ts
bindings/js-web/tests/agent-grok.test.ts
bindings/js-web/tests/agent-openai.test.ts

While creating example apps, I found that it would be more convenient to support multimodal input conversion from `File`, `ArrayBuffer` or `Uint8Array<ArrayBufferLike>` which are often used in javascript frontends.

[WASM] add helper functions for multimodal user content conversion

---

bindings/js-web/src/models/localModel.ts
docs/src/components/CodePreview/style.module.scss
vm/src/model_cache.cpp
vm/src/model_cache.hpp

Added `skip_integrity_check` to disable sha1 integrity check during model download.
It's used in js-web since sha1 computation in browser shows poor performance.

add `skip_integrity_check` in `download_model`

---

Cargo.lock
v2/Cargo.toml
v2/build.rs
v2/shim/CMakeLists.txt

This PR aims to simplify the previous complex build system:
1. Removed the use of cxx-build on the Rust side. Instead, all CXX code generation is unified under CMake using `cxxbridge-cmd`.
2. Configured the build to produce `tvm_runtime.a`, so that Rust, Python, and Node no longer need to link against `tvm_runtime.so` explicitly.

update build system

---

Cargo.lock
v2/Cargo.toml
v2/src/agent.rs
v2/src/cache/from_cache.rs
v2/src/lib.rs
v2/src/model/api/mod.rs
v2/src/model/api/openai.rs
v2/src/model/language_model.rs
v2/src/model/local/chat_template.rs
v2/src/model/local/inferencer.rs
v2/src/model/local/local_language_model.rs
v2/src/model/local/tokenizer.rs
v2/src/tool/builtin.rs
v2/src/tool/mcp/native.rs
v2/src/tool/mcp/wasm32.rs
v2/src/tool/mod.rs
v2/src/utils/maybe_sync.rs
v2/src/utils/mod.rs

This PR applies a patched version of [maybe-sync](https://docs.rs/maybe-sync/latest/maybe_sync/) to remove duplicated codes originiated from `Send` and `Sync`.

Reduce duplicates using maybe-sync

---

.vscode/settings.json
Cargo.lock
v2/Cargo.toml
v2/bindings/python/ailoy/_core.pyi
v2/build.rs
v2/src/agent.rs
v2/src/ffi/py/value.rs
v2/src/model/api/gemini.rs
v2/src/model/api/mod.rs
v2/src/model/local/local_language_model.rs
v2/src/tool/mcp/common.rs
v2/src/tool/mcp/native.rs
v2/src/tool/mcp/wasm32.rs
v2/src/utils/log.rs
v2/src/utils/mod.rs
v2/src/utils/test.rs
v2/src/value/formats.rs
v2/src/value/message.rs
v2/src/value/part.rs

This PR adds Gemini functionalities with the same coverage as in cpp.
In addition, some utilities are included to make multi-platform tests more simpler.
- To make a test runnable on both native and browser, just wrap it with `multi_platform_test!` macro.
- Use `crate::utils::log` to print logs in both native and browser.
- Reads `GEMINI_API_KEY` env var from `.env` at compile time, and forward it on both native and browser tests.
It requires https://github.com/flachesis/gemini-rust/pull/7 to be merged in order to run on wasm. Until then, it's downloaded from our forked repo.

Enable Gemini

---

v2/src/knowledge_base/api/chroma.rs
v2/src/tool/builtin.rs
v2/src/tool/mcp/native.rs
v2/src/tool/mcp/wasm32.rs
v2/src/tool/mod.rs
v2/src/utils/maybe_sync.rs

Tool trait's `.run()` is now async and does not need to return `BoxFuture`.
But it still needs to be dyn compatible, so applied `multi_platform_async_trait`.

tools: replace Arc<Self> with self

---

v2/src/agent.rs
v2/src/model/api/anthropic.rs
v2/src/model/api/gemini.rs
v2/src/model/api/openai.rs
v2/src/model/api/openai_chat_completion.rs
v2/src/model/api/xai.rs
v2/src/model/language_model.rs
v2/src/model/local/local_language_model.rs

previous trait spec:
```
pub trait LanguageModel: MaybeSend + MaybeSync + 'static {
fn run(
self: Arc<Self>,
msg: Vec<Message>,
tools: Vec<ToolDesc>,
) -> BoxStream<'static, Result<MessageOutput, String>>;
}
```
to
```
pub trait LanguageModel: MaybeSend + MaybeSync {
fn run<'a>(
self: &'a mut Self,
msg: Vec<Message>,
tools: Vec<ToolDesc>,
) -> BoxStream<'a, Result<MessageOutput, String>>;
}
```
So that it is not necessary to force Arc<dyn LanguageModel> as a container type(+ do not force stream lifetime to static)

change language model trait to mutable ref

---

v2/shim_js/src/embedding_model.ts
v2/shim_js/src/language_model.ts

In #179, `TVMRuntime` as the common part of LanguageModel and EmbeddingModel is added.
In the process of separating the content from the existing logic, there was a part that deviated from the TVM scope management logic. This PR includes fixes of this.
And additionally, there is another refactoring: constructor of `KVCache` now gets only TVMRuntime object instead of getting the separated tvm, vm, and metadata objects.

fix: consider object disposal scopes

---

v2/src/utils/log.rs

Add macros wrapping log functions can be used like `print!()`.
macro names could be changed.

Formatted log
